# Generated by Django 3.2.1 on 2021-06-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_reply_subscribe'),
        ('posts', '0007_auto_20210601_2034'),
    ]

    operations = [
    ]
