# Generated by Django 3.2.3 on 2021-06-02 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_merge_20210602_1555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForrbiddenWord',
            new_name='ForbiddenWord',
        ),
        migrations.RenameField(
            model_name='subscribe',
            old_name='cat',
            new_name='category',
        ),
    ]
